# Publish wheels to PyPI.
name: "Publish to PyPI"

on:
  workflow_call:

permissions: {}

jobs:
  publish:
    name: "publish"
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
      attestations: write
      contents: read
    steps:
      - name: "Download wheels"
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: wheels
          path: dist/

      - name: "List wheels"
        run: ls -la dist/

      - name: "Generate attestations"
        uses: actions/attest-build-provenance@e8998f949152b193b063cb0ec769d69d929409be # v2.4.0
        with:
          subject-path: dist/*

      - name: "Publish to PyPI"
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
        with:
          packages-dir: dist/
